# Generated by Django 6.0.5 on 2026-08-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
    ]
