# Generated by Django 6.0.5 on 2026-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profilee_phone_customerbooking_serviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
