# Generated by Django 6.0.5 on 2026-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_profilee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('USER', 'User'), ('SERVICE_PROVIDER', 'ServiceProvider')], max_length=20),
        ),
    ]
