# Generated by Django 6.0.5 on 2026-08-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_addservice_category_addservice_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
