# Generated by Django 6.0.5 on 2026-08-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_addservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilee',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
